services:
  db:
    image: postgres:alpine3.18
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp ${DB_HOST}:${DB_PORT} -t 30s -i 250ms

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    links:
      - db
